// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr5ZONXIIi_eIBrdOYAS9WvR0hiVEQkkA',
    appId: '1:896737658368:web:8abfb4a9fbafd7cc003ae5',
    messagingSenderId: '896737658368',
    projectId: 'unipod-5a0f8',
    authDomain: 'unipod-5a0f8.firebaseapp.com',
    storageBucket: 'unipod-5a0f8.appspot.com',
    measurementId: 'G-X058785YNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsyPDQWfE9si-RHLinsqRse8PdalQebkM',
    appId: '1:896737658368:android:5d8c1d500e9bfb48003ae5',
    messagingSenderId: '896737658368',
    projectId: 'unipod-5a0f8',
    storageBucket: 'unipod-5a0f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMzAzEnm-HHxJGjbR1QQKTOCFpmlWr7-0',
    appId: '1:896737658368:ios:85b6cd91dcd645fd003ae5',
    messagingSenderId: '896737658368',
    projectId: 'unipod-5a0f8',
    storageBucket: 'unipod-5a0f8.appspot.com',
    iosClientId: '896737658368-dlsh2vcn3154oeuvibrmc5l9v9o7ta8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.unipod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMzAzEnm-HHxJGjbR1QQKTOCFpmlWr7-0',
    appId: '1:896737658368:ios:a2d0aa9825fe8aee003ae5',
    messagingSenderId: '896737658368',
    projectId: 'unipod-5a0f8',
    storageBucket: 'unipod-5a0f8.appspot.com',
    iosClientId: '896737658368-5f7jgr65hj2h82m57srkulbs415497ii.apps.googleusercontent.com',
    iosBundleId: 'com.example.unipod',
  );
}
