// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT6gukdku4kHO18alUDoUce6Skur9oO8U',
    appId: '1:1027941086185:web:23c79fa588e1ae1ff1d178',
    messagingSenderId: '1027941086185',
    projectId: 'kcroz-dating-app',
    authDomain: 'kcroz-dating-app.firebaseapp.com',
    storageBucket: 'kcroz-dating-app.appspot.com',
    measurementId: 'G-YZ6L4E0BTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrhBvgEZOSsNiqkMrJ-n6UoaZ61ZfKXRs',
    appId: '1:1027941086185:android:38a3212f79a97313f1d178',
    messagingSenderId: '1027941086185',
    projectId: 'kcroz-dating-app',
    storageBucket: 'kcroz-dating-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYxbNn65MWBMvzG8xZ2G3kqpVPEsdem6I',
    appId: '1:1027941086185:ios:e9053435ad3613a7f1d178',
    messagingSenderId: '1027941086185',
    projectId: 'kcroz-dating-app',
    storageBucket: 'kcroz-dating-app.appspot.com',
    iosClientId: '1027941086185-s6bmh5knodevji7akvbi441439q51mo2.apps.googleusercontent.com',
    iosBundleId: 'com.creed.kcroz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYxbNn65MWBMvzG8xZ2G3kqpVPEsdem6I',
    appId: '1:1027941086185:ios:e9053435ad3613a7f1d178',
    messagingSenderId: '1027941086185',
    projectId: 'kcroz-dating-app',
    storageBucket: 'kcroz-dating-app.appspot.com',
    iosClientId: '1027941086185-s6bmh5knodevji7akvbi441439q51mo2.apps.googleusercontent.com',
    iosBundleId: 'com.creed.kcroz',
  );
}
